declare module "*.html";
declare module "*.css";
declare module "*.ts";
declare module "*.tsx";
declare module 'express';
declare module 'ts-node';
import 'jquery-ui';
import 'jquery-ui-dist';
import 'jquery';
import 'webpack';
import 'iconv';
import 'typescript-eslint/no-unsafe-call';
import 'typescript-eslint';
import '@rollup/plugin-json';
import '@typescript-eslint/parser';
